# frozen_string_literal: true

require_relative "src/ruby/tormenta20/version"

Gem::Specification.new do |spec|
  spec.name = "tormenta20"
  spec.version = Tormenta20::VERSION
  spec.authors = ["LuanGB"]
  spec.email = ["luan.goncbs@gmail.com"]

  spec.summary = "Ruby library with data about the Brazilian TTRPG Tormenta20"
  spec.description = "Ruby library providing ActiveRecord models backed by a bundled SQLite database " \
                     "with spells, classes, origins, deities, powers, equipment, races and conditions " \
                     "from the Tormenta20 system."
  spec.homepage = "https://yggdrasilgeeknetwork.github.io/tormenta20/"
  spec.license = "MIT"
  spec.required_ruby_version = ">= 3.0.0"

  spec.metadata["homepage_uri"]       = spec.homepage
  spec.metadata["source_code_uri"]    = "https://github.com/YggdrasilGeekNetwork/tormenta20"
  spec.metadata["changelog_uri"]      = "https://github.com/YggdrasilGeekNetwork/tormenta20/blob/main/CHANGELOG.md"
  spec.metadata["documentation_uri"]  = "https://rubydoc.info/gems/tormenta20"

  spec.files = Dir[
    "src/ruby/**/*",
    "db/schema.sql",
    "docs/ruby/**/*",
    "LICENSE.txt",
    "README.md",
    "CHANGELOG.md"
  ].select { |f| File.file?(f) }

  # Include pre-built database (generated by rake build_db)
  db_file = "db/tormenta20.sqlite3"
  spec.files << db_file if File.exist?(File.join(__dir__, db_file))
  spec.bindir = "exe"
  spec.executables = spec.files.grep(%r{\Aexe/}) { |f| File.basename(f) }
  spec.require_paths = ["src/ruby"]

  # Uncomment to register a new dependency of your gem
  spec.add_dependency "activerecord", "~> 8.0"
  spec.add_dependency "activesupport", "~> 8.0"
  spec.add_dependency "sqlite3", "~> 2.0"

  spec.add_development_dependency "yard"

  # For more information and examples about making a new gem, check out our
  # guide at: https://bundler.io/guides/creating_gem.html
end
